# The default config, edit and save as conf.toml

# Any discord related config, you really only need your token here.
[discord]
token = "discord.token.right-here"

# Roles for everything, like colors, stream notifs, etc.
# key is what they type in to get the role with a command,
# string is the name of the role itself in Discord.
[roles]
	# Staff roles, in case you have different names for other levels of staff.
	[roles.staff]
	admin = "Admin"
	moderator = "Mod"
	member = "Friend"

	# Color roles that users can give themselves.
	[roles.colors]
	white  = "White"
	turq   = "Turquoise"
	green  = "Green"
	sky    = "Sky"
	purple = "purple"
	red    = "Red"
	orange = "Orange"
	yellow = "Yellow"
	dark   = "Dark"
	pink   = "Pink"
	blue   = "Blue"

	# Roles for stream notifications. Not case sensitive
	[roles.streams]
	apex    = "ApexStream"  # https://www.twitch.tv/notquiteapex
	kigu    = "KiguStream"  # https://www.twitch.tv/batkigu
	juici   = "JuiciStream" # https://www.twitch.tv/juicibit
	percy   = "PercyStream" # https://www.twitch.tv/percy_creates
	alchana = "AlchanaStream" # https://www.twitch.tv/alkana

	# Roles for pronouns.
	[roles.pronouns]
	theythem = "they/them"
	sheher   = "she/her"
	hehim    = "he/him"

# channel names for some debugging stuff, not needed but they help with issues.
[dev]
botdev = "bot-dev"
botdms = "bot-dms"
botlog = "bot-logs"
